[package]
name = "rust"
version = "0.1.0"
authors = ["tanay-pingalkar <tpingalkar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"